version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...          
      - docker build -t simultaneously:latest -f containers/app-base.dockerfile containers --build-arg YARN_VERSION=1.13.0 --build-arg RUBY_VERSION=$RUBY_VERSION --build-arg NODE_MAJOR=$NODE_MAJOR --build-arg BUNDLER_VERSION=$BUNDLER_VERSION
      - docker build -t ${IMAGE_REPO_NAME}-web:$IMAGE_TAG -f containers/app-web.dockerfile .
      - docker tag ${IMAGE_REPO_NAME}-web:$IMAGE_TAG $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${IMAGE_REPO_NAME}:$IMAGE_TAG
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com/${IMAGE_REPO_NAME}:$IMAGE_TAG
