shared:
  api_key: <%= Rails.application.credentials.twitter&.[](:api_key) %>
  api_secret: <%= Rails.application.credentials.twitter&.[](:api_secret) %>
test:
  api_key: dummy_api_key
  api_secret: dummy_api_secret
